config/routes.rb
Rails.application.routes.draw do

  namespace :vagrant do
    resources :boxes do
      resources :versions, module: 'boxes' do
        resources :providers, module: 'versions'
      end
    end
  end

end

app/models/vagrant/box/version.rb
class Vagrant::Box::Version < ActiveRecord::Base
  belongs_to :box
  has_many :providers

  def to_s
    self.version
  end
end

app/models/vagrant/box/version/provider.rb
class Vagrant::Box::Version::Provider < ActiveRecord::Base
  belongs_to :version

  def to_s
    self.name
  end
end

app/controllers/vagrant/box/providers_controller.rb
class Vagrant::Box::ProvidersController < ApplicationController
  before_action :set_vagrant_box_provider, only: [:show, :edit, :update, :destroy]

  # GET /vagrant/box/providers
  # GET /vagrant/box/providers.json
  def index
    @vagrant_box_providers = Vagrant::Box::Provider.all
  end

  # GET /vagrant/box/providers/1
  # GET /vagrant/box/providers/1.json
  def show
  end

  # GET /vagrant/box/providers/new
  def new
    @vagrant_box_provider = Vagrant::Box::Provider.new
  end

  # GET /vagrant/box/providers/1/edit
  def edit
  end

  # POST /vagrant/box/providers
  # POST /vagrant/box/providers.json
  def create
    @vagrant_box_provider = Vagrant::Box::Provider.new(vagrant_box_provider_params)

    respond_to do |format|
      if @vagrant_box_provider.save
        format.html { redirect_to @vagrant_box_provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @vagrant_box_provider }
      else
        format.html { render :new }
        format.json { render json: @vagrant_box_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vagrant/box/providers/1
  # PATCH/PUT /vagrant/box/providers/1.json
  def update
    respond_to do |format|
      if @vagrant_box_provider.update(vagrant_box_provider_params)
        format.html { redirect_to @vagrant_box_provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @vagrant_box_provider }
      else
        format.html { render :edit }
        format.json { render json: @vagrant_box_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vagrant/box/providers/1
  # DELETE /vagrant/box/providers/1.json
  def destroy
    @vagrant_box_provider.destroy
    respond_to do |format|
      format.html { redirect_to vagrant_box_providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vagrant_box_provider
      @vagrant_box_provider = Vagrant::Box::Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vagrant_box_provider_params
      params.require(:vagrant_box_provider).permit(:name, :url)
    end
end

app/controllers/vagrant/box/versions_controller.rb
class Vagrant::Box::VersionsController < ApplicationController
  before_action :set_vagrant_box_version, only: [:show, :edit, :update, :destroy]

  # GET /vagrant/box/versions
  # GET /vagrant/box/versions.json
  def index
    @vagrant_box_versions = Vagrant::Box::Version.all
  end

  # GET /vagrant/box/versions/1
  # GET /vagrant/box/versions/1.json
  def show
  end

  # GET /vagrant/box/versions/new
  def new
    @vagrant_box_version = Vagrant::Box::Version.new
  end

  # GET /vagrant/box/versions/1/edit
  def edit
  end

  # POST /vagrant/box/versions
  # POST /vagrant/box/versions.json
  def create
    @vagrant_box_version = Vagrant::Box::Version.new(vagrant_box_version_params)

    respond_to do |format|
      if @vagrant_box_version.save
        format.html { redirect_to @vagrant_box_version, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @vagrant_box_version }
      else
        format.html { render :new }
        format.json { render json: @vagrant_box_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vagrant/box/versions/1
  # PATCH/PUT /vagrant/box/versions/1.json
  def update
    respond_to do |format|
      if @vagrant_box_version.update(vagrant_box_version_params)
        format.html { redirect_to @vagrant_box_version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @vagrant_box_version }
      else
        format.html { render :edit }
        format.json { render json: @vagrant_box_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vagrant/box/versions/1
  # DELETE /vagrant/box/versions/1.json
  def destroy
    @vagrant_box_version.destroy
    respond_to do |format|
      format.html { redirect_to vagrant_box_versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vagrant_box_version
      @vagrant_box_version = Vagrant::Box::Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vagrant_box_version_params
      params.require(:vagrant_box_version).permit(:version, :status, :description_html, :description_markdown, :providers_id)
    end
end

app/controllers/vagrant/boxes/versions/providers_controller.rb
class Vagrant::Boxes::Versions::ProvidersController < ApplicationController
  before_action :set_vagrant_box_version
  before_action :set_vagrant_box_version_provider, only: [:show, :edit, :update, :destroy]

  # GET /vagrant/boxes/providers
  # GET /vagrant/boxes/providers.json
  def index
    @vagrant_box_version_providers = Vagrant::Box::Version::Provider.all
  end

  # GET /vagrant/boxes/providers/1
  # GET /vagrant/boxes/providers/1.json
  def show
  end

  # GET /vagrant/boxes/providers/new
  def new
    @vagrant_box_version_provider = Vagrant::Box::Version::Provider.new
    # @vagrant_box_version_provider.box_id = params[:box_id]
    @vagrant_box_version_provider.version_id = params[:box_id]
  end

  # GET /vagrant/boxes/providers/1/edit
  def edit
  end

  # POST /vagrant/boxes/providers
  # POST /vagrant/boxes/providers.json
  def create
    @vagrant_box_version_provider = Vagrant::Box::Version::Provider.new(vagrant_box_version_provider_params)

    respond_to do |format|
      if @vagrant_box_version_provider.save
        format.html { redirect_to vagrant_box_version_provider_path(@vagrant_box, @vagrant_box_version, @vagrant_box_version_provider), notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @vagrant_box_version_provider }
      else
        format.html { render :new }
        format.json { render json: @vagrant_box_version_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vagrant/boxes/providers/1
  # PATCH/PUT /vagrant/boxes/providers/1.json
  def update
    respond_to do |format|
      if @vagrant_box_version_provider.update(vagrant_box_version_provider_params)
        format.html { redirect_to @vagrant_box_version_provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @vagrant_box_version_provider }
      else
        format.html { render :edit }
        format.json { render json: @vagrant_box_version_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vagrant/boxes/providers/1
  # DELETE /vagrant/boxes/providers/1.json
  def destroy
    @vagrant_box_version_provider.destroy
    respond_to do |format|
      format.html { redirect_to vagrant_box_version_providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_vagrant_box_version
      @vagrant_box_version = Vagrant::Box::Version.find(params[:version_id])
      @vagrant_box = @vagrant_box_version.box
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_vagrant_box_version_provider
      @vagrant_box_version_provider = Vagrant::Box::Version::Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vagrant_box_version_provider_params
      params.require(:vagrant_box_version_provider).permit(:name, :url, :version_id)
    end
end

app/controllers/vagrant/boxes/versions_controller.rb
class Vagrant::Boxes::VersionsController < ApplicationController
  before_action :set_vagrant_box
  before_action :set_vagrant_box_version, only: [:show, :edit, :update, :destroy]

  # GET /vagrant/boxes/1/versions
  # GET /vagrant/boxes/1/versions.json
  def index
    @vagrant_box_versions = Vagrant::Box::Version.all
  end

  # GET /vagrant/boxes/versions/1
  # GET /vagrant/boxes/versions/1.json
  def show
  end

  # GET /vagrant/boxes/versions/new
  def new
    @vagrant_box_version = Vagrant::Box::Version.new
    @vagrant_box_version.box_id = params[:box_id]
  end

  # GET /vagrant/boxes/versions/1/edit
  def edit
  end

  # POST /vagrant/boxes/versions
  # POST /vagrant/boxes/versions.json
  def create
    @vagrant_box_version = Vagrant::Box::Version.new(vagrant_box_version_params)

    respond_to do |format|
      if @vagrant_box_version.save
        format.html { redirect_to @vagrant_box_version, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @vagrant_box_version }
      else
        format.html { render :new }
        format.json { render json: @vagrant_box_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vagrant/boxes/versions/1
  # PATCH/PUT /vagrant/boxes/versions/1.json
  def update
    respond_to do |format|
      if @vagrant_box_version.update(vagrant_box_version_params)
        format.html { redirect_to @vagrant_box_version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @vagrant_box_version }
      else
        format.html { render :edit }
        format.json { render json: @vagrant_box_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vagrant/boxes/versions/1
  # DELETE /vagrant/boxes/versions/1.json
  def destroy
    @vagrant_box_version.destroy
    respond_to do |format|
      format.html { redirect_to vagrant_box_versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_vagrant_box
      @vagrant_box = Vagrant::Box.find(params[:box_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_vagrant_box_version
      @vagrant_box_version = Vagrant::Box::Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vagrant_box_version_params
      params.require(:vagrant_box_version).permit(:version, :status, :description_html, :description_markdown, :box_id)
    end
end

app/helpers/vagrant/box/providers_helper.rb
module Vagrant::Box::ProvidersHelper
end

app/helpers/vagrant/box/versions_helper.rb
module Vagrant::Box::VersionsHelper
end

app/views/vagrant/boxes/versions/providers/_form.html.erb
<%= form_for(@vagrant_box_version_provider) do |f| %>
  <% if @vagrant_box_version_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vagrant_box_version_provider.errors.count, 'error') %> prohibited this vagrant_box_provider from being saved:</h2>

      <ul>
      <% @vagrant_box_version_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :version_id %><br>
    <%= f.text_field :version_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vagrant/boxes/versions/providers/edit.html.erb
<h1>Editing vagrant_box_provider</h1>

<%= render 'form' %>

<%= link_to 'Show', vagrant_box_version_provider_path(@vagrant_box, @vagrant_box_version, @vagrant_box_version_provider) %> |
<%= link_to 'Back', vagrant_box_version_providers_path %>

app/views/vagrant/boxes/versions/providers/index.html.erb
<h1>Listing vagrant_box_providers</h1>

<table>
  <thead>
    <tr>
      <th>Seq</th>
      <th>Name</th>
      <th>Url</th>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vagrant_box_version_providers.each do |vagrant_box_version_provider| %>
      <tr>
        <td><%= vagrant_box_version_provider.id %></td>
        <td><%= vagrant_box_version_provider.name %></td>
        <td><%= vagrant_box_version_provider.url %></td>
        <td><%= vagrant_box_version_provider.version %></td>
        <td><%= link_to 'Show', vagrant_box_version_provider_path(@vagrant_box, @vagrant_box_version, vagrant_box_version_provider) %></td>
        <td><%= link_to 'Edit', edit_vagrant_box_version_provider_path(@vagrant_box, @vagrant_box_version, vagrant_box_version_provider) %></td>
        <td><%= link_to 'Destroy', vagrant_box_version_provider_path(@vagrant_box, @vagrant_box_version, vagrant_box_version_provider), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_vagrant_box_version_provider_path %>

app/views/vagrant/boxes/versions/providers/new.html.erb
<h1>New vagrant_box_provider</h1>

<%= render 'form' %>

<%= link_to 'Back', vagrant_box_version_providers_path %>

app/views/vagrant/boxes/versions/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vagrant_box_version_provider.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @vagrant_box_version_provider.url %>
</p>

<%= link_to 'Edit', edit_vagrant_box_version_provider_path(@vagrant_box, @vagrant_box_version, @vagrant_box_version_provider) %> |
<%= link_to 'Back', vagrant_box_version_providers_path %>